name: "Docker build"
description: "Builds the Docker image."

inputs:
  ghcr-token:
    description: Token of current GitHub account in GitHub container registry.
    required: false
    default: ""
  dockerhub-user:
    description: "User name for the DockerHub account"
    required: false
    default: ""
  dockerhub-token:
    description: Token for the DockerHub account
    required: false
    default: ""
  push:
    description: Should push the docker image or not.
    required: false
    default: "false"
  image-name:
    description: The basic name of docker.
    required: false
    default: "halo"
  console-ref:
    description: The Git ref of console project.
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        cache: "gradle"
        java-version: 17
    - name: Setup console environment
      uses: halo-sigs/actions/admin-env-setup@main
    - name: Build Console
      shell: bash
      run: |
        make cbuild
    - name: Reset version of Halo
      if: github.event_name == 'release'
      shell: bash
      run: |
        # Set the version with tag name when releasing
        version=${{ github.event.release.tag_name }}
        version=${version#v}
        sed -i "s/version=.*-SNAPSHOT$/version=$version/1" gradle.properties
    - name: Build with Gradle
      shell: bash
      run: |
        ./gradlew downloadPluginPresets
        ./gradlew clean build -x check -x jar
    - name: DockerHub image
      id: dockerhub-image
      run: |
        if [ -z ${{ inputs.dockerhub-user }} ]
        then
          echo "docker_image=" >> $GITHUB_OUTPUT
        else
          echo "docker_image=halohub/${{ inputs.image-name }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Docker meta for Halo
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}
          ${{ steps.dockerhub-image.outputs.docker_image }}
        tags: |
          type=schedule,pattern=nightly-{{date 'YYYYMMDD'}},enabled=${{ github.event_name == 'schedule' }}
          type=ref,event=branch,enabled=${{ github.event_name == 'push' }}
          type=semver,pattern={{ version }}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,enabled=${{ github.event_name == 'push' }}
        flavor: |
          latest=false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      if: inputs.ghcr-token != '' && github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.ghcr-token }}
    - name: Login to DockerHub
      if: inputs.dockerhub-token != '' && github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-user }}
        password: ${{ inputs.dockerhub-token }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        push: ${{ (inputs.ghcr-token != '' || inputs.dockerhub-token != '') && inputs.push == 'true' }}
